processes:
  - "UpdateDiscoveryArtifacts"
  - "RegenerateReadme"
  - "DiscoveryDocUpdate"
  - "PythonDependency"
  - "PythonSampleDependency"
  - "NodeDependency"
  - "NodeRelease"
  - "JavaApiaryCodegen"
  - "JavaDependency"
  - "OwlBotTemplateChanges"
  - "OwlBotAPIChanges"
  - "PHPApiaryCodegen"
