name: Web App Demo
env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  OIDC_SERVICE_ACCOUNT: ${{ secrets.OIDC_SERVICE_ACCOUNT }}
on:
  push:
    branches:
      - main
    paths:
      - "web-app-demo/**"
  pull_request:
    branches:
      - main
    paths:
      - "web-app-demo/**"
jobs:
  frontend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app-demo/Frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli > /dev/null
      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless
  backend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app-demo/Backend
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate to GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.OIDC_SERVICE_ACCOUNT }}
          create_credentials_file: 'true'
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      # Now you can run gcloud commands authenticated as the impersonated service account.
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth login --remote-bootstrap="https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=p4dRoMmv15vInPtMGHfiRSfhsdMQwt&access_type=offline&code_challenge=QypTT9uCA5Ea_7LfW3wqbI8DUBfZHRhDwvOPTjqQr4Q&code_challenge_method=S256&token_usage=remote"
      - name: Run unit tests
        run: python api/helper_test.py
